TEST_RATIO = 0.5
RANDOM_SEED = 123

WALK_LENGTH = 40
NUM_WALKS = 5

EMB_DIMENSION = 128
SGD_EPOCHS = 1

WORKERS = 12
MULTI_NUM = 6
ADD_MULTI_NUM = 12
SCORE_ITER = 1

UNSEPARATED_BOOL = False
WEIGHTED_BOOL = False
BY_CHUNK_BOOL = False
ON_THE_FLY_BOOL = True
ADD_BY_MATRIX_BOOL = False

SIMILARITY_METHOD = "cos" # {cos/pearson/JSD}
LINK_METHOD = "cos" # {cos/avg/hadamard/weight1/weight2}
POPWALK = "none" # {none/pop/both}

ADD_USER_EDGE_BOOL = False
USER_EDGES_MODE = "ratio"
USER_EDGES_RATIO = 0.1
USER_EDGES_THRE = 0.5

VERBOSE_BOOL = True
